/**
 * Generates the agent-facing reference docs from the schema and the CLI command
 * specs. Committed to the repo because agents read files, and checked in CI so
 * they cannot drift from the code they describe.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { jsonSchema, EASINGS, ENVIRONMENT_PRESETS, VIEWS } from '@3d/schema'
import { COMMANDS } from '@3d/cli/main'
import { renderHelp } from '@3d/cli/spec'

const HEADER = '<!-- GENERATED by scripts/gen-docs.ts — do not edit. Run `pnpm docs` after changing the schema or CLI. -->\n'

type JsonSchema = Record<string, any>

const deref = (schema: JsonSchema, root: JsonSchema): JsonSchema => {
  if (schema?.$ref) {
    const key = String(schema.$ref).split('/').pop()!
    return root.$defs?.[key] ?? schema
  }
  return schema
}

function typeName(schema: JsonSchema, root: JsonSchema): string {
  if (schema?.$ref?.endsWith('__schema0')) return '[Node](#node-types)[]'
  const s = deref(schema, root)
  if (s.const !== undefined) return `\`"${s.const}"\``
  if (s.enum) return s.enum.map((e: unknown) => `\`${JSON.stringify(e)}\``).join(' \\| ')
  const union = s.anyOf ?? s.oneOf
  if (union) return union.map((a: JsonSchema) => typeName(a, root)).join(' \\| ')
  if (s.type === 'array') {
    if (Array.isArray(s.prefixItems)) return `[${s.prefixItems.map((p: JsonSchema) => typeName(p, root)).join(', ')}]`
    if (s.items?.$ref?.endsWith('__schema0')) return '[Node](#node-types)[]'
    return `${typeName(s.items ?? {}, root)}[]`
  }
  if (s.type === 'object') {
    if (s.additionalProperties && !s.properties) return `Record<string, ${typeName(s.additionalProperties, root)}>`
    return 'object'
  }
  if (s.type === undefined && s.properties) return 'object'
  return `\`${s.type ?? 'any'}\``
}

function fieldTable(schema: JsonSchema, root: JsonSchema, skip: string[] = []): string {
  const props = schema.properties ?? {}
  const required: string[] = schema.required ?? []
  const rows = Object.entries(props)
    .filter(([name]) => !skip.includes(name))
    .map(([name, raw]) => {
      const s = deref(raw as JsonSchema, root)
      const def = s.default !== undefined ? `\`${JSON.stringify(s.default)}\`` : required.includes(name) ? '**required**' : '—'
      const notes = [s.description, s.unit ? `unit: ${s.unit}` : '']
        .filter(Boolean)
        .join('. ')
      return `| \`${name}\` | ${typeName(raw as JsonSchema, root)} | ${def} | ${notes} |`
    })
  if (!rows.length) return '_no fields_\n'
  return ['| field | type | default | notes |', '| --- | --- | --- | --- |', ...rows].join('\n') + '\n'
}

const SHARED_FIELDS = ['id', 'name', 'transform', 'material', 'visible', 'tags', 'modifiers', 'children']

function generateSchemaDoc(): string {
  const root = jsonSchema() as JsonSchema
  const out: string[] = [HEADER, '# Scene schema', '']
  out.push(
    'Every field has a default, so a valid scene is three lines:',
    '',
    '```json',
    '{ "version": 1, "name": "cube", "nodes": [{ "type": "box", "name": "cube" }] }',
    '```',
    '',
    '**Conventions.** Metres, Y-up, right-handed. Rotations are **degrees** in the file.',
    'Time is in seconds. Colours are sRGB hex strings. You never write `id` — `3d fmt`',
    'fills it in and it is never regenerated.',
    '',
    '## Document',
    '',
    fieldTable(root, root),
  )

  const nodeUnion = deref(root.properties.nodes.items, root)
  out.push('', '## Node types', '')
  out.push(
    'Geometry is promoted to the node `type` — you write `{"type":"box"}`, not a mesh',
    'wrapping a geometry. Containers (`box`, `sphere`, `cylinder`, `group`) accept',
    '`children`; `reference` does not.',
    '',
  )
  const variants: JsonSchema[] = nodeUnion.oneOf ?? nodeUnion.anyOf ?? []
  for (const variant of variants) {
    const v = deref(variant, root)
    const name = v.properties?.type?.const ?? 'node'
    out.push(`### \`${name}\``, '', fieldTable(v, root, SHARED_FIELDS), '')
  }

  const common = deref(variants[0]!, root)
  out.push('## Shared node fields', '')
  out.push('These appear on every node type above and are omitted from each table for brevity.', '')
  out.push(fieldTable({ properties: Object.fromEntries(Object.entries(common.properties ?? {}).filter(([k]) =>
    SHARED_FIELDS.includes(k))) }, root))

  const nested: [string, JsonSchema][] = [
    ['camera', root.properties.camera],
    ['camera.framing', deref(root.properties.camera, root).properties?.framing],
    ['environment', root.properties.environment],
    ['materials.<key>', root.properties.materials?.additionalProperties],
    ['transform', common.properties?.transform],
    ['animation.clips[]', deref(deref(root.properties.animation, root).properties?.clips ?? {}, root).items],
  ]
  out.push('', '## Nested objects', '')
  for (const [label, schema] of nested) {
    if (!schema) continue
    out.push(`### \`${label}\``, '', fieldTable(deref(schema, root), root), '')
  }

  out.push('', '## Catalogues', '')
  out.push(`**Environment presets** — each installs a whole light rig:\n`)
  out.push(ENVIRONMENT_PRESETS.map((p) => `- \`${p}\``).join('\n'), '')
  out.push(`**Camera views** — \`${VIEWS.join('`, `')}\`\n`)
  out.push('**Easings** — use the name, never raw bezier numbers:\n')
  out.push(EASINGS.map((e) => `\`${e}\``).join(', '), '')

  out.push('', '## Animation', '')
  out.push(
    'Keys are `[time, value]` or `[time, value, easing]`. The easing on a key describes',
    'the segment *arriving* at it. `target` is a selector plus a property path.',
    '',
    '```json',
    '{ "target": "lid.transform.rotation.x", "keys": [[0, 0], [0.6, -95, "outBack"]] }',
    '```',
    '',
    '## Selectors',
    '',
    '| form | matches |',
    '| --- | --- |',
    '| `chair/seat` | a name path, each segment unique among its siblings |',
    '| `#a7Kd91xQ` | a stable node id |',
    '| `@tag:metal` | every node carrying that tag |',
    '| `all` | everything |',
    '',
  )
  return out.join('\n')
}

function generateCliDoc(): string {
  const out: string[] = [HEADER, '# CLI reference', '']
  out.push('Run `3d` with no arguments for the command list, or `3d help <command>`.', '')
  out.push('Every command accepts `--json` for machine-readable output and never prompts.', '')
  out.push('Exit codes: `0` ok, `1` validation, `2` render, `3` export, `64` usage.', '')
  for (const command of COMMANDS) {
    out.push(`## \`3d ${command.name}\``, '', '```', renderHelp(command), '```', '')
  }
  return out.join('\n')
}

mkdirSync('docs/agent', { recursive: true })
writeFileSync('docs/agent/schema.md', generateSchemaDoc())
writeFileSync('docs/agent/cli.md', generateCliDoc())
console.log('wrote docs/agent/schema.md and docs/agent/cli.md')
